markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]
title : Felwig Software
production_url : http://felwig.com/
description: ""
# analytics: UA-32899481-1
# gauges: 50f2b533613f5d7c8000000c
author :
  name : Felwig Software
  github : felwig
  twitter : felwig
  email: felwig@gmail.com
